### ISSUE TITLE
[1.18.2] Striders movement is severely affected by canary

### ISSUE THREAD

**Issue by Flyte-less** [AbdElAziz333/Canary#47] opened 2022-11-11 20:17 UTC
### Version Information

canarymc1.18.2-0.0.9

### Expected Behavior

Striders should be able to swim through lava at a decently fast pace when riding one with a saddle and warped fungus on a stick.

### Actual Behavior

The strider seems to bob up and down and even travels slower through lava than on land.

### Reproduction Steps

1. Dig out a decently sized hole and fill it with lava. It does not need to be deep.
2. Spawn in a strider in the lava and equip it with a saddle.
3. Hold a fungus on a stick to point the strider in the direction of travel.
4. Notice the discrepancy with strider movement in vanilla, also note the speed of the strider out of lava in comparison.

### Other Information

No other mods seem to be relevant to this issue.

https://cdn.discordapp.com/attachments/726317267058556960/1040721376828477540/nomods.mp4
https://cdn.discordapp.com/attachments/726317267058556960/1040721377738629150/canary.mp4

**Comment by AbdElAziz333** [comment] 2022-11-11 23:06
can you please test this build ?

**Comment by AbdElAziz333** [comment] 2022-11-11 23:08
can you please test this [build](https://github.com/AbdElAziz333/Canary/releases/tag/mc1.19.2-v0.1.0-BETA)?

**Comment by Flyte-less** [comment] 2022-11-12 01:08
seems like everything works here.

**Comment by AbdElAziz333** [comment] 2022-11-16 22:34
The issue is fixed in both 0.1.1 for MC 1.19.2 and 0.0.10 for MC 1.18.2.
Good Luck!

**Closed by AbdElAziz333** 2022-11-16 22:34 UTC
Labels: bug, vanilla parity, pending release
