### ISSUE TITLE
1.19.2 latest update crash with Create ponder

### ISSUE THREAD

**Issue by CzarTheOwlman** [AbdElAziz333/Canary#112] opened 2023-03-06 21:02 UTC
------------------------

### Version
>
> canary-mc1.19.2-0.1.9.jar
> 
### Reproduction Steps

> Used Create's ponder feature on the portable storage interface, and halfway through the animation the game crashed

### Crash Report File
[crash-2023-03-06_15.40.48-client.txt](https://github.com/AbdElAziz333/Canary/files/10902687/crash-2023-03-06_15.40.48-client.txt)

### Additional Information

> As far as I can see from the log, looks like there's a conflict with Canary's entity collision feature.

**Comment by anarisis** [comment] 2023-03-06 22:10
Same issue. Pretty consistently reproduceable.

Crash report:
https://bytebin.lucko.me/dMQOM9zrCj

**Comment by DrUltraLux** [comment] 2023-03-07 01:57
Had the same issue yesterday also.

**Comment by kawaiicakes** [comment] 2023-03-09 19:48
Getting this issue as well.

**Comment by TheInfamousAlk** [comment] 2023-03-22 02:23
Me too!
[crash-2023-03-21_22.09.01-client.txt](https://github.com/AbdElAziz333/Canary/files/11035616/crash-2023-03-21_22.09.01-client.txt)

**Comment by Urmus-dev** [comment] 2023-03-30 22:33
It also craches on 0.1.9 when looking at gantry moving. Going back to 0.1.8 solves it.

**Comment by Branjoman** [comment] 2023-04-01 14:58
I'm seeing the same issue as well, and I think I've narrowed the issue down a bit as it doesn't affect every ponder. From my testing, any ponder that tries to put an item entity into it will crash (the chute ponder, for example), whereas ponders that don't are unaffected. Hopefully this new info will help towards fixing the core issue.

**Comment by AbdElAziz333** [comment] 2023-04-03 18:53
Fixed in my side, the release will updated soon.

**Comment by ahmettcavus** [comment] 2023-04-08 13:40
can confirm also

**Comment by DarkSolus** [comment] 2023-04-09 21:11
easily fixable by adding the following lines to canary.properties

`mixin.entity.collisions=false`
`mixin.entity.gravity_check_block_below=false`

No idea which one fixes the bug, I decided better safe than sorry.

**Comment by AbdElAziz333** [comment] 2023-04-20 00:50
can you please use the new update?
[1.19.4](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498538) - [1.19.3](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498537) - [1.19.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498536) - [1.18.2](https://legacy.curseforge.com/minecraft/mc-mods/canary/files/4498539)

**Comment by shadow7483147** [comment] 2023-04-20 03:36
> can you please use the new update?

Yep! It no longer crashes, though the item entity is not visible while pondering.

**Comment by lynnpye** [comment] 2023-04-24 14:07
> > can you please use the new update?
> 
> Yep! It no longer crashes, though some items are not visible while pondering. (Encased fan: gold ingot/nugget example; the tooltip icons still show up at least)

Looks like the following setting allows the item to be visible again (specifically tested the encased fan scenario):

`mixin.entity.collisions.movement=false`

**Closed** 2023-05-24 21:44 UTC
Labels: modded incompatbility, pending release, critical bug
