### ISSUE TITLE
The hopper connected to the composter does not work in version  McVer1.8.2 ModVer【 0.1.7 , 0.1.9  ,0.1.10 , 0.2.0 , 0.2.1】

### ISSUE THREAD

**Issue by u7f8au7fbd** [AbdElAziz333/Canary#155] opened 2023-05-29 03:08 UTC
After posting an issue in the past with a similar problem, it was merged with other hopper issues. This issue has been resolved, but in versions other than 0.1.8, the composter sometimes does not work after adding plant-based items, such as hoppers. I am reporting this because I believe the problem still remains with hoppers.

**Comment by biochemie** [comment] 2023-05-30 13:48
Recently saw a regression (I presume?) after updating Canary to 1.18.2-0.2.1. The server (Forge 1.18.2) was previously running 0.1.8 and hopper insertion into composters was working as intended by vanilla mechanics. 

After updating to 0.2.1 hoppers were no longer able to insert into composters from hoppers interacting through the top of the composter. Output from composters and insertion into vanilla furnaces remained unaffected.

Disabling the hopper mixin (`mixin.block.hopper=false`) resolves the issue.

**Comment by u7f8au7fbd** [comment] 2023-05-31 00:22
Thanks for the information. I would like to continue with that method of dealing with the problem temporarily.

**Comment by MrJorman** [comment] 2023-05-31 04:02
yes . too problem, Forge 1.19.2 composter no working.

**Comment by biochemie** [comment] 2023-06-15 01:29
Appears to be resolved with the new 0.2.2 update. Confirmed on my 1.18.2 server. Disabling of the hopper mixin no longer required. Thank you greatly @AbdElAziz333!

**Closed** 2023-06-18 08:24 UTC
Labels: pending release
