### ISSUE TITLE
[1.19.2] Game Crash when connecting to Server

### ISSUE THREAD

**Issue by Chaos02** [AbdElAziz333/Canary#52] opened 2022-11-16 08:19 UTC
### Version

> canary-mc1.19.2-0.0.10.jar

### Reproduction Steps

> join a (Spigot 1.19.2) server
> The Mod combination works totally fine in single player.

### Crash Report File

> [crash-2022-11-15_09.58.56-client.txt](https://github.com/AbdElAziz333/Canary/files/10019477/crash-2022-11-15_09.58.56-client.txt)

### Additional Information

Mod list:

> I suspect the crash comes from the combination of rubidium and canary

```
3dskinlayers-forge-1.5.2-mc1.19.1.jar
appleskin-forge-mc1.19-2.4.2.jar
balm-4.5.3.jar
BetterF3-4.0.0-Forge-1.19.2.jar
betterfpsdist-1.19.1-1.6.jar
Bookshelf-Forge-1.19.2-16.1.9.jar
canary-mc1.19.2-0.0.10.jar
cloth-config-8.2.88-forge.jar
collective-1.19.2-5.16.jar
configured-2.0.1-1.19.2.jar
connectivity-1.19.2-3.4.jar
Controlling-forge-1.19.2-10.0+7.jar
craftingtweaks-forge-1.19-15.1.0.jar
CullLessLeaves-1.0.6.jar
Ding-1.19.2-1.3.0.jar
DistantHorizons-1.6.9a-1.19.2.jar
dynview-1.19.1-2.9.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar
entityculling-forge-1.5.2-mc1.19.1.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
farsight-1.19.2-2.1.jar
ferritecore-5.0.2-forge.jar
fuelgoeshere-1.19.2-0.1.0.0.jar
GameMenuModOption-1.19-1.18.jar
harvestwithease-1.19.2-4.0.0.2-forge.jar
InventoryHud_[1.19.2].forge-3.4.6.jar
Jade-1.19.1-forge-8.4.1.jar
jei-1.19.2-forge-11.4.0.285.jar
JustEnoughProfessions-forge-1.19-2.0.1.jar
JustEnoughResources-1.19.2-1.1.0.179.jar
MouseTweaks-forge-mc1.19-2.23.jar
musicdr-3.0.0.jar
oculus-mc1.19.2-1.2.8.jar
okzoomer-forge-1.19-2.1.1.jar
rubidium-0.6.2.jar
RubidiumExtra-1.19.2-0.4.11.44.jar
screenshot-to-clipboard-1.0.9-forge.jar
smoothboot(reloaded)-mc1.19.2-0.0.1.jar
spark-1.9.45-forge.jar
stackrefill_1.19.2-3.2.jar
starlight-1.1.1+forge.cf5b10b.jar
textrues_rubidium_options-1.0.3-Hotfix-mc1.19.2.jar
```

**Comment by Chaos02** [comment] 2022-11-16 15:21
I believe this is not a duplicate - I cannot find any issues containing "connect" or "server" in this context!

**Comment by AbdElAziz333** [comment] 2022-11-16 22:36
can you use this [build](https://www.curseforge.com/minecraft/mc-mods/canary/files/4091544)?

**Comment by JetyWawoo** [comment] 2022-11-17 00:03
> can you use this [build](https://www.curseforge.com/minecraft/mc-mods/canary/files/4091544)?

Now not only does the forge server not start, but now I can't even launch the game client-side without disabiling Canary like #54.
Client debug: [debug.log](https://github.com/AbdElAziz333/Canary/files/10026527/debug.log)
Server debug: [debug.log](https://github.com/AbdElAziz333/Canary/files/10026522/debug.log)
Additionally, this was what the startup command prompt said:
<details>
  <summary>Click to expand</summary>
  [18:56:03] [main/INFO] [minecraft/DataFixers]: Building unoptimized datafixer [18:56:04] [main/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin [18:56:04] [main/FATAL] [mixin/]: Mixin apply failed canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin -> net.minecraft.world.level.chunk.LevelChunk: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on setBlockEntityTickingOrder could not find any targets matching 'lambda$updateBlockEntityTicker$7' in net.minecraft.world.level.chunk.LevelChunk. Using refmap canary.refmap.json [PREINJECT Applicator Phase -> canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin -> Prepare Injections ->  -> handler$bef000$setBlockEntityTickingOrder(Lnet/minecraft/world/level/block/entity/BlockEntity;Lnet/minecraft/world/level/block/entity/BlockEntityTicker;Lnet/minecraft/core/BlockPos;Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/block/entity/TickingBlockEntity;Ljava/lang/Object;)V -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on setBlockEntityTickingOrder could not find any targets matching 'lambda$updateBlockEntityTicker$7' in net.minecraft.world.level.chunk.LevelChunk. Using refmap canary.refmap.json [PREINJECT Applicator Phase -> canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin -> Prepare Injections ->  -> handler$bef000$setBlockEntityTickingOrder(Lnet/minecraft/world/level/block/entity/BlockEntity;Lnet/minecraft/world/level/block/entity/BlockEntityTicker;Lnet/minecraft/core/BlockPos;Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/block/entity/TickingBlockEntity;Ljava/lang/Object;)V -> Parse] at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {} at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {} at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2363!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {} at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar%2354!/:10.0.8+10.0.8+main.0ef7e830] {} at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {} at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {} at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {} at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {} at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {} at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {} at net.minecraft.core.GlobalPos.m_122641_(GlobalPos.java:11) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-5.0.28.jar%2375!/:?] {} at net.minecraft.core.GlobalPos.<clinit>(GlobalPos.java:11) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at net.minecraft.world.entity.ai.memory.MemoryModuleType.<clinit>(MemoryModuleType.java:31) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B} at net.minecraft.world.entity.animal.frog.Tadpole.<clinit>(Tadpole.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:252) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A} at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,re:classloading,pl:mixin:APP:repurposed_structures.mixins.json:features.DungeonFeatureAccessor,pl:mixin:A} at net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilMixin,pl:mixin:A} at net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:resources.BuiltInRegistriesMixin,pl:mixin:A} at net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:resources.BuiltInRegistriesMixin,pl:mixin:A} at java.util.LinkedHashMap.forEach(LinkedHashMap.java:729) ~[?:?] {} at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:repurposed_structures.mixins.json:resources.BuiltInRegistriesMixin,pl:mixin:A} at net.minecraft.core.Registry.<clinit>(Registry.java:665) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:mixin,re:classloading} at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading} at net.minecraft.server.Main.main(Main.java:110) ~[server-1.19.2-20220805.130853-srg.jar%23225!/:?] {re:classloading,re:mixin,pl:mixin:A} at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {} at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {} at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.1.52.jar%2367!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {} at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {} Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) at java.base/java.lang.reflect.Method.invoke(Method.java:578) at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.52/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ... 7 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.GlobalPos.m_122641_(GlobalPos.java:11) at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.GlobalPos.<clinit>(GlobalPos.java:11) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.memory.MemoryModuleType.<clinit>(MemoryModuleType.java:31) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.animal.frog.Tadpole.<clinit>(Tadpole.java:54) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:252) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.<clinit>(MonsterRoomFeature.java:26) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.feature.Feature.<clinit>(Feature.java:81) at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.AquaticFeatures.<clinit>(AquaticFeatures.java:20) at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.features.FeatureUtils.m_236677_(FeatureUtils.java:24) at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87) at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114) at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:729) at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113) at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:665) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:110) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ... 10 more Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin] from phase [DEFAULT] in config [canary.mixins.json] FAILED during APPLY at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ... 41 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on setBlockEntityTickingOrder could not find any targets matching 'lambda$updateBlockEntityTicker$7' in net.minecraft.world.level.chunk.LevelChunk. Using refmap canary.refmap.json [PREINJECT Applicator Phase -> canary.mixins.json:world.block_entity_ticking.sleeping.LevelChunkMixin -> Prepare Injections ->  -> handler$bef000$setBlockEntityTickingOrder(Lnet/minecraft/world/level/block/entity/BlockEntity;Lnet/minecraft/world/level/block/entity/BlockEntityTicker;Lnet/minecraft/core/BlockPos;Ljava/lang/Object;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/world/level/block/entity/TickingBlockEntity;Ljava/lang/Object;)V -> Parse] at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ... 41 more Press any key to continue . . .
</details>

**Comment by AbdElAziz333** [comment] 2022-11-17 08:19
fixed in the new [version](https://www.curseforge.com/minecraft/mc-mods/canary/files/4092142).

**Comment by AbdElAziz333** [comment] 2022-12-25 13:39
Can you try this [update](https://www.curseforge.com/minecraft/mc-mods/canary/files/4260201)?

**Comment by AbdElAziz333** [comment] 2023-01-03 00:09
should be fixed in the new updates.
[1.19.3](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291690) - [1.19.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291688) - [1.18.2](https://www.curseforge.com/minecraft/mc-mods/canary/files/4291687) .
Good luck!

**Closed by AbdElAziz333** 2023-01-03 00:09 UTC
Labels: bug, pending release
