### ISSUE TITLE
Crash on Ticking Entity

### ISSUE THREAD

**Issue by LunarPhobos** [AbdElAziz333/Canary#25] opened 2022-10-20 20:00 UTC
**Version:** Forge 1.19.2 | 43.1.43
**Mod Version:** 1.19.2-0.0.5
**Steps to Reproduce:**
-Run the above versions
-Create a world with seed 6598908739288654486
-Fly around until you crash
[Crash Report](https://hastebin.com/ixogivibuv.properties)

**Comment by originalusername32** [comment] 2022-10-20 21:36
Also encountered this when trying to find the cause of another issue
[crash-2022-10-20_16.25.03-server.txt](https://github.com/AbdElAziz333/Canary/files/9834055/crash-2022-10-20_16.25.03-server.txt)
Downgrading to version 0.0.4 prevented it from recurring

**Comment by AbdElAziz333** [comment] 2022-10-20 21:43
fixed in 0.0.6 update.

**Closed by AbdElAziz333** 2022-10-20 21:43 UTC
