### ISSUE TITLE
[1.18.2]Mowzie's Mobs sunstrikes cause server lag

### ISSUE THREAD

**Issue by 6371peter** [AbdElAziz333/Canary#15] opened 2022-09-30 12:12 UTC
Version
canary-mc1.18.2-0.0.7
mowziesmobs-1.5.29
Forge-1.18.2-40.1.80

Reproduction Steps
 1.Download canary and mowziesmobs
 2.Find Barako spawns
 3.Make Barako use sunstrike,then server lag

**Comment by AbdElAziz333** [comment] 2022-09-30 13:13
duplicate of #11 and #12.

**Comment by AbdElAziz333** [comment] 2022-09-30 18:23
Sorry, its not duplicate issue, i will look into this.

**Comment by AbdElAziz333** [comment] 2022-11-15 14:56
for now you can set `mixin.entity.fast_retrieval=false` in canary.properties in the config file.

**Comment by AbdElAziz333** [comment] 2022-11-16 07:06
fixed in the coming version.

**Comment by AbdElAziz333** [comment] 2022-11-16 22:32
The issue is fixed in both 0.1.1 for MC 1.19.2 and 0.0.10 for MC 1.18.2.
I hope you have a good day!

**Closed by AbdElAziz333** 2022-11-16 22:32 UTC
Labels: bug, modded incompatbility, pending release
