### ISSUE TITLE
1.19.2 - Forge 43.1.52 - Never Starts Up  ``Failed to Apply Mixins``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AbdElAziz333/Canary#54] opened 2022-11-16 23:31 UTC
Forge Version 43.1.52
canary-mc1.19.2-0.1.1

Latest.log
https://gist.github.com/P3rf3ctXZer0/0fcdb0a638aeee4d44ee70db02fd4e9b

The game starts up if I use canary-mc1.19.2-0.0.9 anything past this has the issue listed below.

Talking to Thutmose this is the fail point 

https://gist.github.com/P3rf3ctXZer0/e19edca83c8a17ba4a3b5903daa3d24a

**Comment by P3rf3ctXZer0** [comment] 2022-11-16 23:51
![sBGhP0m 1](https://user-images.githubusercontent.com/10351221/202319882-42ddd7d4-ef1e-4f28-8711-45fd7c2ec7c8.png)

**Comment by BugmanBugman** [comment] 2022-11-17 00:20
getting this as well

**Comment by Foozey** [comment] 2022-11-17 02:03
I'm also getting mixin crashes with the latest update.

**Comment by oxoct** [comment] 2022-11-17 02:30
same with me

**Comment by Quadnick** [comment] 2022-11-17 03:24
Same errors for my 1.19.2 server as well

**Comment by TheDogeOfTheInternet** [comment] 2022-11-17 06:45
The log provided shows that this is the same issue as described [here](https://github.com/AbdElAziz333/Canary/issues/51#issuecomment-1317658522).

AbdElAziz333 [described the fix as being](https://github.com/AbdElAziz333/Canary/issues/51#issuecomment-1317746568):
> in LevelChunkMixin you should replace lambda$updateBlockEntityTicker$7 with m_187960_ and in common.entity.EntityClassGroup you should replace canCollideWith with m_7337_ and canBeCollidedWith with m_5829_.

To me, this seems to suggest that it's some sort of reobfuscation oversight. Surely there should be some automated way of building such that the exported mod uses the obfuscated names in Minecraft rather than the deobfuscated names available with MCP.

**Comment by AbdElAziz333** [comment] 2022-11-17 07:19
i forgot changing the method names to SRG names, i am very sorry about that.

**Comment by TheDogeOfTheInternet** [comment] 2022-11-17 07:48
> i forgot changing the method names to SRG names, i am very sorry about that.

I'm not an expert at Minecraft Forge or the Minecraft modding system in general, but shouldn't you be able to build such that you don't need to manually change between deobfuscated names and SRG names?

Looking at the Minecraft Forge source code, there seems to be a way to implement `hasMethodOverride()` in `ReflectionUtil` to avoid this issue: if you call `clazz.getDeclaredMethod(ObfuscationReflectionHelper.remapName(INameMappingService.Domain.METHOD, methodNameInSRG), methodArgs)` (as seen [here](https://github.com/MinecraftForge/MinecraftForge/blob/0e66b7b21757e510aef706ca320881b9eb268822/fmlcore/src/main/java/net/minecraftforge/fml/util/ObfuscationReflectionHelper.java#L145), using Forge's ObfuscationReflectionHelper and INameMappingService classes) instead of the [current `clazz.getDeclaredMethod(methodName, methodArgs)`](https://github.com/AbdElAziz333/Canary/blob/8f6d69366c56876fc71fc9d5ae5676ddec923126/src/main/java/com/abdelaziz/canary/common/reflection/ReflectionUtil.java#L10-L13), I think this would mean you would only have to store the SRG names in the code, but the dev builds would also work due to the remapping. I'm not 100% sure, but it might be good to try.

I'm not so sure about the lambda one in LevelChunkMixin, since I was under the impression that @Inject was meant to remap everything automatically. However, looking at [these docs](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Obfuscation-and-Mixins), they mention that inner classes can have issues with deobfuscation. I'm not 100% sure how lambdas are implemented in Java, but the $ notation seems potentially suggestive of inner classes to me. The docs say that it can be resolved for private inner class _fields_ by using an `aliases` value in an @Shadow or @Overwrite annotation, but since you use this inside an @Inject annotation, I'm not sure if it's possible to do so. Maybe it would be worth asking on the Minecraft Forge forums or something if this is possible.

**Comment by AbdElAziz333** [comment] 2022-11-17 08:14
I will try that, i really appreciate your help!

**Comment by AbdElAziz333** [comment] 2022-11-17 08:16
The issue is fixed in the new [version](https://www.curseforge.com/minecraft/mc-mods/canary/files/4092142).

**Closed by AbdElAziz333** 2022-11-17 08:16 UTC
Labels: pending release

**Comment by AbdElAziz333** [comment] 2022-11-22 11:19
@TheDogeOfTheInternet Thanks for your suggestion it get worked! I hope you have a good day!
