### ISSUE TITLE
[1.19.2] Moving the hopper with a piston (Quark feature) causes a crash.

### ISSUE THREAD

**Issue by MihailDenisov** [AbdElAziz333/Canary#48] opened 2022-11-12 12:29 UTC
**Version**

> canary-mc1.19.2-0.0.9.jar

**Reproduction Steps**

> 1. Set the hopper and piston side by side.
> 2. Activate the piston
> 3. During the proposed movement of the piston, the server will stop

**Crash Report**

[crash-2022-11-12_14.45.01-server.txt](https://github.com/AbdElAziz333/Canary/files/9994954/crash-2022-11-12_14.45.01-server.txt)

**Additional information**

> Accurately tested on sticky pistons. After removing the canary, the Quark feature works properly. Adding the hopper (minecraft:hopper) to the blacklist of movable objects in the Quark configuration does not allow the hopper to be moved, thus solving the problem.
> Using Quark version: Quark-3.3-371

**Comment by AbdElAziz333** [comment] 2022-11-12 12:56
duplicate of #44, please before opening a new issue make sure its not duplicate issue.

**Closed** 2022-11-12 15:18 UTC
Labels: bug, duplicate, modded incompatbility
