### ISSUE TITLE
Error on server start with Canary

### ISSUE THREAD

**Issue by dylanharty** [AbdElAziz333/Canary#20] opened 2022-10-06 17:09 UTC
### Reproduction Steps
Just starting a fairly vanilla forge server with create mod, pluto, smooth boot, canary. Running JAVA 17.

### Crash Report File
attached.
[error-on-start.txt](https://github.com/AbdElAziz333/Canary/files/9727018/error-on-start.txt)

### Additional Information
Once I remove the canary mod this error with not be present.

**Comment by AbdElAziz333** [comment] 2022-10-06 20:58
could you please send me the full latest.log so i can get more information?

**Comment by HellishINC** [comment] 2022-10-08 13:08
This seems like a duplicate of #14 since the section of log is nearly identical.

**Comment by dylanharty** [comment] 2022-10-15 16:56
@AbdElAziz333 We can close this issue if you guys cannot reproduce. We have moved onto fabric instead of forge. I do not have the original log file and have not setup a new forge server. This issue was on Debian 11 if that matters.

**Comment by AbdElAziz333** [comment] 2022-10-16 07:30
For now idk what makes this issue occurs, i don't understand the issue for now.

**Comment by AbdElAziz333** [comment] 2022-10-18 20:21
This issue is not from Canary because i tested it in some server hosting servers, you maybe created the server with the wrong method.

**Closed by AbdElAziz333** 2022-10-18 20:21 UTC
Labels: needs information

**Comment by Speiger** [comment] 2022-11-09 15:06
@AbdElAziz333 this usually happens due to corruption in the uploaded jar.
Have you tried downloading your own mod and installing it that way?
